const socketEvents = {
  USER_DETAILS: "USER_DETAILS",
  CREATE_CHAT_ROOM: "CREATE_CHAT_ROOM",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  WEB_RTC_SIGNAL: "WEB_RTC_SIGNAL",
  CALL: "CALL",
  CALL_NOTIFICATION: "CALL_NOTIFICATION",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_REJECTED: "CALL_REJECTED",
  CALL_READY: "CALL_READY",
  NOTIFICATION: "NOTIFICATION",
  ONLINE_USERS: "ONLINE_USERS",
  UPDATE_ONLINE_USERS: "ONLINE_USER",
};

export default socketEvents;
