const socketEvents = {
  USER_DETAILS: "USER_DETAILS",
  CREATE_CHAT_ROOM: "CREATE_CHAT_ROOM",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  WEB_RTC_OFFER: "WEB_RTC_OFFER",
  WEB_RTC_ANSWER: "WEB_RTC_ANSWER",
  NOTIFICATION: "NOTIFICATION",
};

export default socketEvents;
